multipath-tools: Autospec creation for update from version 0.9.3 to version 0.9.4
Benjamin Marzinski (8):
      libmultipath: impove add_feature() variable names
      multipathd: don't initialize the field width in show_path()
      libmultipath: improve remove_feature() variable names
      multipath.conf(5): remove io-affinity information
      libmpathpersist: fix command keyword ordering
      libmpathutil: simplify set_value and validate_config_strvec
      libmultipath: don't leak memory on invalid strings
      libmutipath: validate the argument count of config strings

Martin Wilck (48):
      fixup! Makefile.inc: fix man and include paths
      multipath-tools: Makefile.inc: Fix paths for systemd
      multipath-tools: Makefile.inc: don't take values from environment
      multipath-tools: Makefile.inc: get rid of RUN
      multipath-tools: Makefile.inc: more compact code for LIB
      multipath-tools: Makefiles: simplify code for include dirs
      multipath-tools: Makefiles: use $(mandir)
      multipath-tools: Makefile.inc: simplify expression for SYSTEMD
      multipath-tools: Makefile.inc: untangle paths and source directories
      multipath-tools: Makefiles: replace $(libdir) by $(plugindir)
      multipath-tools: Makefile.inc: use simple make variables consistently
      multipath-tools: Makefile.inc: fix a log message
      multipath-tools: Makefile.inc: set systemd-specific flags
      multipathd: Makefile: fix compilation flags for libedit
      multipath-tools Makefiles: clean up executable Makefiles
      multipath-tools: Makefiles: use common code for libraries
      multipath-tools: Makefiles: move common code to rules.mk
      multipath-tools Makefiles: create config.mk
      multipath-tools Makefiles: enable quiet build
      multipath-tools: quiet build support for top-level Makefile
      GitHub workflows: use make -j8 -Orecurse
      README.md: Move section about libedit and libreadline
      README.md: Fix indentation in paragraph about device handlers
      README.md: document options for paths and optimization
      README.md: document how to customize build
      libmultipath: avoid -Warray-bounds error with gcc 12 and musl libc
      multipath: avoid NULL string in released_to_systemd()
      libmultipath: avoid NULL string in is_udev_ready()
      multipath.conf(5): remove deprecated note for san_path_err algorithm
      multipath.conf(5): improve documentation of dev_loss_tmo
      multipath-tools tests: Makefile: dump output in case of failure
      multipath-tools Makefile: fix compilation on Ubuntu trusty
      libdmmp: allow installing without perl
      multipath-tools Makefiles: fix variable passing to sub-make
      multipath-tools: create-config.mk: Test _FORTIFY_SOURCE=2, too
      multipath-tools: create-config.mk: fix logic for building autoconfig.h
      multipath-tools: README.md: document passing CFLAGS etc to the build process
      multipath-tools: tests/directio: fix failure wuith MUSL libc on s390x
      multipathd: fix compilation error on Centos 7
      libmpmathutil: fix compilation issue for clock_gettime()
      libmultipath: fix call of udev_device_unref() for old libudev
      multipath-tools: detect presence of libjson-c
      GitHub workflows: use new build containers from ghcr.io
      GitHub workflows: disable fail-fast strategy
      GitHub workflows: multiarch.yaml: add i386
      GitHub workflows: run tests for rolling distros on schedule
      fixup! multipath-tools Makefile: fix compilation on Ubuntu trusty
      libmultipath: bump version to 0.9.4

Masanari Iida (1):
      kpartx_id: Add missing 3rd option in usage

Paul Koetsier (1):
      libmultipath: fix 'show paths format' failure

Xose Vazquez Perez (7):
      multipath-tools: add EF to rdac info
      multipath-tools: multipath.conf man page housekeeping
      multipath-tools: update hwtable text/info/comments
      multipath-tools: add PowerMax NVMe to hwtable
      multipath-tools: add more info for NetApp ontap prio
      multipath-tools: fix c&p error in install_keyword for deprecated pg_timeout
      multipath-tools: mailing list url was changed